apiVersion: v1
kind: Service
metadata:
  name: sr-svc
  namespace: sr-ns
  labels:
    env: poc
spec:
  type: NodePort
  selector:
    env: poc
  ports:  
    - port: 5000   # port = service port
      targetPort: 80  # container Port = target Port 
      nodePort: 32000  # we can assign any port in between the range of 30000-32766




