apiVersion: v1
kind: PersistentVolume
metadata:
  name: sr-pv
  namespace: sr-ns
  labels:
    env: poc
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ysrcp"



