apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sr-pvc
  namespace: sr-ns
  labels:
    env: poc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


