apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: sr-ns
  labels:
    env: poc
type: Opaque
data:
  sql_alchemy_conn: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Jvb3Q6cm9vdEBwb3N0Z3Jlcy1haXJmbG93OjU0MzIvYWlyZmxvdw==

